# Generated by Django 6.0.7 on 2026-08-29 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=100)),
                ("usersex", models.CharField(max_length=10)),
                ("userschool", models.CharField(max_length=20)),
                ("userinterest", models.TextField(blank=True, null=True)),
                ("userthought", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "myapp_userprofile",
            },
        ),
        migrations.DeleteModel(
            name="Students",
        ),
    ]
