# Generated by Django 6.0.7 on 2026-08-26 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TemperatureRecord",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("sensor_id", models.IntegerField()),
                ("temperature", models.FloatField()),
                ("humidity", models.FloatField()),
                ("timestamp", models.DateTimeField()),
            ],
            options={
                "db_table": "myapp_temperature_db",
            },
        ),
        migrations.DeleteModel(
            name="Students",
        ),
    ]
