# Generated by Django 6.0.7 on 2026-08-27 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_temperaturerecord_delete_students"),
    ]

    operations = [
        migrations.RenameField(
            model_name="temperaturerecord",
            old_name="id",
            new_name="myid",
        ),
    ]
