# Generated by Django 6.0.7 on 2026-08-19 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("aID", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=32)),
            ],
            options={
                "db_table": "myapp_author",
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                ("cID", models.AutoField(primary_key=True, serialize=False)),
                ("cName", models.CharField(max_length=20)),
                ("cSex", models.CharField(default="F", max_length=1)),
                ("cBirthday", models.DateField(blank=True, null=True)),
                ("cEmail", models.CharField(max_length=100)),
                ("cPhone", models.CharField(max_length=50)),
                ("cAddr", models.CharField(max_length=255)),
                ("cHeight", models.IntegerField(blank=True, null=True)),
                ("cWeight", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "myapp_student",
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("isbn", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=32)),
                ("authors", models.ManyToManyField(to="myapp.author")),
            ],
            options={
                "db_table": "myapp_book",
            },
        ),
        migrations.CreateModel(
            name="Scorelist",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("course", models.CharField(max_length=20)),
                ("score", models.IntegerField()),
                (
                    "student",
                    models.ForeignKey(
                        db_column="cID",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.student",
                    ),
                ),
            ],
            options={
                "db_table": "myapp_scorelist",
            },
        ),
        migrations.CreateModel(
            name="Permissions",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("passwd", models.CharField(max_length=100)),
                ("level", models.CharField(max_length=2)),
                (
                    "student",
                    models.OneToOneField(
                        db_column="cID",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.student",
                    ),
                ),
            ],
            options={
                "db_table": "myapp_permissions",
            },
        ),
    ]
