# Generated by Django 6.0.7 on 2026-08-13 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Students",
            fields=[
                ("cID", models.AutoField(primary_key=True, serialize=False)),
                ("cName", models.CharField(max_length=20)),
                ("cSex", models.CharField(default="F", max_length=1)),
                ("cBirthday", models.DateField()),
                ("cMail", models.EmailField(max_length=100)),
                ("cPhone", models.CharField(max_length=50)),
                ("cAddr", models.CharField(max_length=255)),
                ("cHeight", models.IntegerField(blank=True)),
                ("cWeight", models.IntegerField(blank=True)),
            ],
        ),
    ]
